### ISSUE TITLE
Add number of nodes and number of acts to output

### ISSUE THREAD

**Issue by christofs** [lehkost/dramavis#13]
I think it would probably be useful (and would certainly not hurt) to add "number of nodes" (= dramatic characters) to the output. They are extracted anyway to calculate some other measures I believe. 
And it wouldn't hurt to have the number of acts in addition to the number of scenes, just to have more complete data.

**Comment by peertrilcke** [comment]
"number of nodes" = "charcount" (https://github.com/lehkost/dramavis/blob/master/dramavis.py#L287) ?

**Comment by christofs** [comment]
True I guess!

**Comment by lehkost** [comment]
I think we can close this one.
